name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        # මෙහි අකුරු නිවැරදිව (Case-sensitive) තිබීම අත්‍යවශ්‍යයි
        uses: Kivy/buildozer-action@master
        with:
          workdir: .
          buildozer_config: buildozer.spec
