name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        # මෙහි අගට තිබූ අමතර 'v' අකුර ඉවත් කර ඇත
        uses: ArtemSerebrennikov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master